#ifndef ENUMS_BANGUN_DATAR_H
#define ENUMS_BANGUN_DATAR_H

enum EnumsBangunDatar {
    PERSEGI_PANJANG = 1,
    PERSEGI,
    LINGKARAN,
    SEGITIGA_SIKU,
    SEGITIGA_SAMA_SISI,
    SEGITIGA_SAMA_KAKI,
    SEGITIGA_SEMBARANG,
    TRAPESIUM,
    JAJAR_GENJANG,
    LAYANG_LAYANG,
    BELAH_KETUPAT,
    KELUAR_BANGUN_DATAR
};

#endif